// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE0qRhLE4U3eOq35quA5YvlgOkJrfS9uw',
    appId: '1:1088170124772:web:55f2418143b726fd5fd3f1',
    messagingSenderId: '1088170124772',
    projectId: 'catalift-task',
    authDomain: 'catalift-task.firebaseapp.com',
    storageBucket: 'catalift-task.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3y71Vg7IrQFpYlJbRb23rwUlCAOnKZk4',
    appId: '1:1088170124772:android:4fdf3f656af3d8fe5fd3f1',
    messagingSenderId: '1088170124772',
    projectId: 'catalift-task',
    storageBucket: 'catalift-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjGQVIwARd8DNSoL_G9vGL-_y086Ob49g',
    appId: '1:1088170124772:ios:f70a64eb52b54e645fd3f1',
    messagingSenderId: '1088170124772',
    projectId: 'catalift-task',
    storageBucket: 'catalift-task.firebasestorage.app',
    iosBundleId: 'com.example.cataliftTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjGQVIwARd8DNSoL_G9vGL-_y086Ob49g',
    appId: '1:1088170124772:ios:f70a64eb52b54e645fd3f1',
    messagingSenderId: '1088170124772',
    projectId: 'catalift-task',
    storageBucket: 'catalift-task.firebasestorage.app',
    iosBundleId: 'com.example.cataliftTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE0qRhLE4U3eOq35quA5YvlgOkJrfS9uw',
    appId: '1:1088170124772:web:df78bc558e82d0415fd3f1',
    messagingSenderId: '1088170124772',
    projectId: 'catalift-task',
    authDomain: 'catalift-task.firebaseapp.com',
    storageBucket: 'catalift-task.firebasestorage.app',
  );
}
